# -*- coding: utf-8 -*-
"""Solcast_API_Work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDGBYQAA6eEeOAuLNReYrXKXwXxL4ixr
"""

import json
import pandas as pd

api_base = 'https://api.solcast.com.au' 

solcast_api_key =  "U7mG4zUHGW3gczhlcZslxE2QiWDOTGJl"
api_key = "U7mG4zUHGW3gczhlcZslxE2QiWDOTGJl"



#function for calling api for World Solar Radiation Data (Estimated actuals by location) 
def world_sol_radiation_data_api:

#GET /world_radiation/forecasts 


#function for calling api for Rooftop 
def rooftop_sites:

#GET /rooftop_sites/{resource_id}/forecasts

#function for calling api for Utility Scale Sites 
def utilty_scale_sites:

#GET /utility_scale_sites/{resource_id}/weather/estimated_actuals
#GET /utility_scale_sites/{resource_id}/estimated_actuals